### ISSUE TITLE
Calendar view?

### ISSUE THREAD

**Issue by kmaustral** [joshuatazrein/obsidian-time-ruler#1]
Congratulations on this impressive plugin. It's amazing that you can integrate Dataview, Tasks and ical. 

There's a big gap in Obsidian currently with calendars. Full Calendar has not worked properly with time zones for a long time now. It would be great to get drag and drop working with Tasks in a Calendar view. 

Personally, I prefer to work with calendar days rather than day hours. TickTick has a good calendar for seeing events and tasks together. It would be great to have this in Obsidian. 

Also, I can't seem to get Tasks to include time and duration. 

I hope this plugin can be developed to cover some the basic needs in Obsidian.

**Comment by claremacrae** [comment]
> Also, I can't seem to get Tasks to include time and duration.

Tasks author/maintainer here...

That's because Tasks doesn't support time and duration.

Also, be aware that if you follow the guidelines of this plugin, your Start and Due date values won't be read by Tasks any more.

https://publish.obsidian.md/tasks/Getting+Started/Auto-Suggest#What%20do%20I%20need%20to%20know%20about%20the%20order%20of%20items%20in%20a%20task?

**Comment by joshuatazrein** [comment]
I've just fixed the error in the plugin's integration with Tasks, thanks @claremacrae  for pointing that out.

I will certainly consider "zooming out" the Tasks view to show a day-by-day view. Currently the "deadlines" tab has a daily Ruler. You can currently drag tasks between days by dragging a task to the buttons above. Additionally if you drag the view to the main Obsidian tab, it will expand to include multiple days at once. 

Thanks for the suggestion! I expect a daily view to come soon.

**Comment by joshuatazrein** [comment]
Time Ruler now has a Calendar View! It's a vertical scroll of days without the hour-markers, as well as calendar-style buttons for easily dragging tasks between days. Enjoy! Let me know if this is what you're looking for or if you have any other suggestions.
