### ISSUE TITLE
Full Calendar Full Note format not being recognized

### ISSUE THREAD

**Issue by technotherion** [joshuatazrein/obsidian-time-ruler#10]
**Describe the bug**
When a task is created via Full Calendar as a Full Note, the task is not recognized by Time Ruler. 

**To Reproduce**
1. Go to Full Calendar settings
2. Add a Full Note calendar
3. Open Full Calendar
4. Create an event using the Full Note calendar
5. Task will not be reflected in Time Ruler

**Expected behavior**
When using a Daily Note calendar, the event syncs as a task during the correct time and duration as expected. 

**Obsidian Version:** 
- [ ] Mobile
- [x] Desktop

My observation is that the plugin may not be looking at metadata information for full notes and may only be expecting inline task information.

**Comment by joshuatazrein** [comment]
This is a feature which will be supported soon. Currently the Full Calendar integration only works with Daily Note tasks, but full notes should be added this week.

**Comment by joshuatazrein** [comment]
I've added these features to the roadmap so am closing the issue for now.
