### ISSUE TITLE
Usage of length DV task field conflicts with TS string length property

### ISSUE THREAD

**Issue by stoilis** [joshuatazrein/obsidian-time-ruler#101]
**Is your feature request related to a problem? Please describe.**
Time Ruler currently supports "length" as a task value to signify how long it lasts, if it doesn't have an endTime.
However, length is a reserved [Typescript word](https://www.tutorialspoint.com/typescript/typescript_string_length.htm).
When I use dataviewjs for advanced queries in obsidian, the conflict becomes more obvious.
For example, this works:
- [ ] something [effort:: 1h]
```
const pages = dv.pages()
const tasks = pages.file.tasks
	.where(t => t.effort)
const total = dv.luxon.Duration.fromMillis(tasks.effort.array().reduce((acc, val) => acc + val, 0)).shiftTo('hours', 'minutes').toHuman()
```

But this doesn't:
- [ ] something [length:: 1h]
```
const pages = dv.pages()
const tasks = pages.file.tasks
	.where(t => t.length)
const total = dv.luxon.Duration.fromMillis(tasks.length.array().reduce((acc, val) => acc + val, 0)).shiftTo('hours', 'minutes').toHuman()
```

**Describe the solution you'd like**
I recommend changing the "length" to something like "effort" or "duration". The duration term is already a [DataView datatype](https://blacksmithgu.github.io/obsidian-dataview/annotation/types-of-metadata/#duration) but it should not be an issue, because the function name is "[dur()](https://blacksmithgu.github.io/obsidian-dataview/reference/literals/#durations)".
If you want to avoid yet another potential conflict, "effort" seems like a better bet. [Some people seem to already by using it this way](https://forum.obsidian.md/t/dataview-js-summing-task-metadata/50874).

**Comment by joshuatazrein** [comment]
That's true and a good point. I can add support for parsing "duration" as well.
