### ISSUE TITLE
Support actions on ICS

### ISSUE THREAD

**Issue by purierca** [joshuatazrein/obsidian-time-ruler#103]
Incorporate (even merge?) [ICS plugin](https://github.com/cloud-atlas-ai/obsidian-ics) functions to super charge usefulness of Time Ruler. And more.

- Clickable events to create new note in Obsidian
- Clickable link in the event title to launch online meeting
- Access to event info: Attendees, invitation content

I'm currently mix and matching Day Planner, ICS, Tasks etc. and it's... too much?

See @feralflora 's great Templater code in ICS for reference. https://github.com/cloud-atlas-ai/obsidian-ics/discussions/74

**Comment by joshuatazrein** [comment]
These could be added for sure. Thanks!
- Creation of new notes with scheduled date (if selecting a parent folder)
- Clickable links & more event info
