### ISSUE TITLE
Only include tasks from current daily note (without Tasks plugin)?

### ISSUE THREAD

**Issue by sachit-menon** [joshuatazrein/obsidian-time-ruler#105]
Hi, thanks for this plugin! I'm new to dataview, and I'm wondering if there's an easy way to only include tasks listed in the current day's daily note under 'today' -- without having metadata inserted into the line for the task with Tasks/Day Planner/etc. Specifically, what I normally write in dataview inline is:

```dataview
TASK
FROM "_Daily Notes"
WHERE file.name = dateformat(date(today), "yyyy-MM-dd")
```

Is this compatible with Time Ruler? It seemed like the default, but my tasks are not showing up in Today unless I manually turn on Tasks or Day Planner. Thanks!

**Comment by joshuatazrein** [comment]
Yes, you would use a custom function using the Dataview JS api under the Filter Function setting.
