### ISSUE TITLE
Incorrect parsing of anchor links

### ISSUE THREAD

**Issue by Sotis-Oph** [joshuatazrein/obsidian-time-ruler#107]
**Describe the bug**
When processing a list of tasks containing anchor links, Time Ruler identifies part of the link as a tag.
If you mark a task as completed, its description is distorted. A new tag appears and the link is broken.
An example can be seen in the attached file and on the screenshot.

**To Reproduce**
1. Create a list of tasks with a anchor links. (Time Ruler does not show the description correctly)
2. Mark the task as completed.

**Expected behavior**
The system must correctly identify references as described in the documentation.
https://help.obsidian.md/Linking+notes+and+files/Internal+links#Link+to+a+heading+in+a+note

**Screenshots**
![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/40307793/7a0d4cc4-ede8-449f-b3f7-a11595fc7fa5)

**Test file**
[Test.md](https://github.com/joshuatazrein/obsidian-time-ruler/files/14812511/Test.md)

**Obsidian Version:** 
- Obsidian Desktop 1.5.11
- Time Ruler 2.2.0

**Additional context**
I corrected the value of the regular expression `TAG_SEARCH = /#[\p{Letter}\/\d_-]+/gu` to `TAG_SEARCH = /(?<!((\[[^(\])]*)|(\[[^\]]+\]\([^\)]*)))#[\p{Letter}\/\d_-]+/gu` and the representation of the task in Time Ruler became correct.
After the task execution the anchor link remained correct, but in the task description there was a new tag that should not be there. (`#Description` tag on the screenshot)
![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/40307793/76805fc3-dfdd-4be5-82c8-a790bc5815da)
Maybe I'm missing something in the parser code...

**Comment by joshuatazrein** [comment]
Thanks for pointing this out—I'll check. To be honest there's a bug in Dataview that recognizes anchor links as tags which complicates the matter. I'll fix in the upcoming release!
