### ISSUE TITLE
Time ruler in main tab doesn't display after restart

### ISSUE THREAD

**Issue by gr2mx** [joshuatazrein/obsidian-time-ruler#110]
**Describe the bug**
After restarting obsidian, if time ruler was open in the main tab, the tab will be empty after restart. Closing and reopening time ruler in main tab will fix it.

**To Reproduce**
1. Open time ruler in main tab
2. Restart Obsidian

**Expected behavior**
Time ruler in main tab should be displayed after an obsidian restart

**Screenshots**

![Screenshot_20240412_073239](https://github.com/joshuatazrein/obsidian-time-ruler/assets/1076494/c25b2c1f-e3dd-4aba-8e36-84872711dd11)

**Obsidian Version:** 
- [ ] Mobile
- [X] Desktop

**Comment by joshuatazrein** [comment]
I'll fix in the next update, thanks!
