### ISSUE TITLE
[FR] Display remaining days

### ISSUE THREAD

**Issue by wwjCMP** [joshuatazrein/obsidian-time-ruler#112]
**Is your feature request related to a problem? Please describe.**

Now for tasks with a due time, only the deadline is displayed, which does not allow for an intuitive understanding of the remaining time.

**Describe the solution you'd like**

For tasks with a due time, display the number of remaining days along with the deadline.

**Describe alternatives you've considered**

**Additional context**

**Comment by joshuatazrein** [comment]
Seems good, I can add in a setting.

**Comment by j-palindrome** [comment]
This has been added in v2.5.0.
