### ISSUE TITLE
[Bug] New Task prepends before frontmatter

### ISSUE THREAD

**Issue by technotherion** [joshuatazrein/obsidian-time-ruler#12]
### Scenario 1:

1. Go to a time on the calendar to create a task and click the + icon.
2. Click a note's pink heading.
3. If the note has any frontmatter, the task will prepend to it, breaking it. 

![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/13829537/b5061720-ad47-4061-b654-86b940a879f6)

### Scenario 2:
1. Go to a time on the calendar and click the + icon.
2. Under a note's pink heading, choose a smaller grey heading.
3. Task will successfully append after the heading associated with the tasks inside of it.

![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/13829537/c82aed56-0ba2-4ad7-8c0a-63d7cdcda6cf)

### Scenario 3: 
1. Go to a time on the calendar and click the + icon.
2. Find a note that has two smaller grey headings under the pink heading. Choose the second grey heading.
3. Instead of inserting under the second associated heading, the task will instead prepend before the frontmatter. 

![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/13829537/d8868fa0-6f66-42c9-ab4e-a047676a2d85)

###Expected behavior: 
In Scenario 1, I would expect:
1. A setting in the plugin asking under what heading I'd like the task to be pasted, or top/bottom of file (Similar to QuickAdd)
2. A dialogue box asking me under which line I would like it pasted (similar to Metadata Menu)
3. Bottom of the file as to avoid frontmatter

In Scenario 3, I would expect behavior similar to Scenario 2.

**Comment by joshuatazrein** [comment]
Thanks for this issue! This is fixed in the upcoming release (1.0.2) as Time Ruler will search for metadata and insert tasks after it. In future I would like to add an option to add tasks at the start or end of headings.
