### ISSUE TITLE
[FR] Delete time block to unassign all tasks within it

### ISSUE THREAD

**Issue by technotherion** [joshuatazrein/obsidian-time-ruler#13]
**Is your feature request related to a problem? Please describe.**
When I create a time block, but something else comes up during my day, it takes many steps to remove multiple start dates from multiple different notes. It would be nice to unassign a start time from the time ruler itself.

**Describe the solution you'd like**
Right click context menu on a timeblock to unassign the entire time block (essentially deleting it), resetting the start time of every task within that timeblock. Additionally, a right click context menu on an individual task to unassign it would be helpful. 

**Describe alternatives you've considered**
Maybe time blocks or tasks could be dragged 'off' of the timeline or up into the unassigned tasks area.

**Comment by joshuatazrein** [comment]
I'll add this to the documentation, but you can drag the horizontal line on top of the date title to reschedule all of those tasks back to the unassigned tasks area. See here:
![dragging-example](https://github.com/joshuatazrein/obsidian-time-ruler/assets/84872947/e5bd33f0-adf4-4e6b-8191-c1412480df1a)

I will add an option to remove scheduling for time blocks as well. Currently Time Ruler doesn't use right-clicks so I might just add a drag target to unschedule everything.

**Comment by joshuatazrein** [comment]
Update: this is fixed in the upcoming release `1.0.3`.
