### ISSUE TITLE
[1.0.2] Headings + Their Tasks sometimes display under wrong note in Search/Create Task Modal

### ISSUE THREAD

**Issue by technotherion** [joshuatazrein/obsidian-time-ruler#14]
For some reason, headings from one note may appear under another note. 

In the following example, you can see that I have a header called Timeblocks and a header called Tasks underneath my 2023-07-23 note.
However, in Time Ruler's task search, neither heading shows up and the task does not appear under search. 

![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/13829537/fa4cf6c9-7da3-4a88-aa7a-fa3d982e7795)

So where did that task and timeblock information go? Well... for some reason it's under my 7/26 daily note. 
![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/13829537/2b7f9a98-cbca-458a-8cf3-e40cdd4c6f09)
 If I cilck the "timeblocks" heading, it takes me to my 7-28 daily note. 

My best guess as to why it would be appearing under 7/26 is because that daily note has a heading called "Time Blocks" with no tasks under it. But that seems bizarre because "timeblocks" != "Time Blocks"... Meanwhile, clicking on Tasks brings me to the correct tasks on 6/26 and the correct tasks are displaying. 

I decided to take this a step further by going to my 7/28 note and adding a task called "test task" under the task heading to see if it shows up. Instead of showing up under 7/28, it showed up underneath a second "Tasks" heading under July 26. Strange...

![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/13829537/e16e50bd-c035-4b55-8c91-7f58564c72f0)

In the unassigned tasks section, the tasks display correctly.

![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/13829537/dd34fb11-f152-4929-a98c-58e1b6c2e17a)

Headers in a note appear to be unrecognized by Time Ruler search unless a task is already underneath it, which I am guessing is expected behavior.  I think maybe something like "always put tasks under Tasks heading or create one if it does not exist" would be helpful in this situation?

**Comment by joshuatazrein** [comment]
Hmm, thought I fixed this bug in `1.0.2`. It definitely should display under the correct note. This might take a bit of thinking why it's not working. Could you upload the plaintext of the daily notes which are acting up so I can try to replicate the issue in a test vault?

**Comment by technotherion** [comment]
Update:
It looks as if this has something to do with today's current daily note. 
For example, here's my 7/29 note: 
![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/13829537/d12524cb-10f9-4386-b01e-f9355fe65f79)

In Time Ruler, it shows that 7/29 has no tasks under it:
![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/13829537/b6b70790-6914-4c38-ab51-e6e45b2b6351)

Here's the tasks, mysteriously hanging out under 7/28:
![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/13829537/9126db17-bb0f-4f58-839c-ba13cc6bce27)

The issues affecting 7/28 in search are now gone, which makes me think that this has something to do with the current date or current daily note. 

Let me know if there's any more information or files I could provide.

**Comment by technotherion** [comment]
Update:
It looks as if this has something to do with today's current daily note. 
For example, here's my 7/29 note: 
![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/13829537/d12524cb-10f9-4386-b01e-f9355fe65f79)

In Time Ruler, it shows that 7/29 has no tasks under it:
![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/13829537/b6b70790-6914-4c38-ab51-e6e45b2b6351)

Here's the tasks, mysteriously hanging out under 7/28:
![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/13829537/9126db17-bb0f-4f58-839c-ba13cc6bce27)

The issues affecting 7/28 in search are now gone, which makes me think that this has something to do with the current date or current daily note. 

Let me know if there's any more information or files I could provide. 

(Ticket closed on accident, re-opening)

**Comment by joshuatazrein** [comment]
Ok, I see the issue in my test vault. The problem is that Time Ruler moves the current daily note to the top, but it failed to move its subheadings. I've fixed the issue in the upcoming release `1.0.3`.
