### ISSUE TITLE
[FR] Re-validate/reset remote calendars command

### ISSUE THREAD

**Issue by technotherion** [joshuatazrein/obsidian-time-ruler#15]
**Is your feature request related to a problem? Please describe.**
I often re-open obsidian or remove and re-add my ical link to get new events to appear in Time Ruler. 

**Describe the solution you'd like**
Similar to Full Calendar, a command that re-validates and/or resets remote calendars.

**Comment by joshuatazrein** [comment]
This is already there, click the "refresh" button.
