### ISSUE TITLE
Completed tasks marked w/ custom status still appear in Task list

### ISSUE THREAD

**Issue by elipousson** [joshuatazrein/obsidian-time-ruler#17]
[Custom Statuses](https://publish.obsidian.md/tasks/Getting+Started/Statuses/Custom+Statuses) are supported in the Tasks plugin as of Tasks 1.23.0 but it looks like they aren't yet supported by Obsidian Time Ruler.

Here are the steps to reproduce to see this issue:

1. Create a new task
2. Mark as forwarded using the ">" character or dropped/cancelled using the "-" character
3. Note the task still appears in the Obsidian Time Ruler side bar

Ideally, I'd expect any tasks marked with the cancelled and forwarded status markers to be excluded from the list of tasks. It is likely appropriate to keep tasks with other custom statuses, e.g. Important ("!"), Half done ("/"), in the list of tasks on the sidebar.

I have only tested this on Desktop although I'm assuming it would also be an issue on mobile.

**Comment by elipousson** [comment]
Whoops! I checked the settings immediately after submitting this issue and realized that you already have support for this option. I'll go ahead and close the issue – thanks for a very useful plugin!

**Comment by joshuatazrein** [comment]
Thanks! Let me know if anything with statuses comes up. Glad you're enjoying the plugin!
