### ISSUE TITLE
Custom Filter Erroring, Documentation, etc 

### ISSUE THREAD

**Issue by technotherion** [joshuatazrein/obsidian-time-ruler#18]
Bug: Upon hitting the reset button after applying a custom filter that is invalid, tasks remain on Time Ruler even after hitting the refresh button. The tasks no longer update to reflect the status of tasks in the notes. Even if a correct query is inserted, it will not update unless the task list was already empty. 
There is otherwise no indication that the custom filter query has failed. 
Once Obsidian is restarted with the invalid query, it does not show any tasks. 

In regards to this issue: https://github.com/joshuatazrein/obsidian-time-ruler/issues/3
You mention ```dv.pages()``` which is a dataviewJS command, but the custom field says "Enable a custom Dataview filter to search tasks" and does not mention if it's regular task queries or if it's js task queries. 
EDIT: I also didn't notice until  much later that you mentioned it only filters out at document level.

### Is it looking for JS? 

Here's a working dataviewjs query that returns 2 results as follows:
```dataviewjs
dv.taskList(dv.pages().file.tasks
.where(t => t.text.includes("#temp")))
```
This is the output I get on the page: 
![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/13829537/3d4a35ea-62b4-46d1-9130-1a44762e3139)

Here's the variations I've tried within Time Ruler:
```dv.taskList(dv.pages().file.tasks
.where(t => t.text.includes("#temp")))```
```dv.pages().file.tasks .where(t => t.text.includes("#temp")```
```.file.tasks .where(t => t.text.includes("#temp")``` 
```.where(t => t.text.includes("#temp")``` 
```t => t.text.includes("#temp")``` 
```t.text.includes("#temp")```


```#temp``` - successfully got the desired results, except it's matching it to the page tags and not the task tags. 


It feels very vague at the moment as to what kind of input it's expecting. 

Tasks on the page, where one is incomplete and does not have the #temp tag:
![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/13829537/400c3149-105d-426a-bce8-502bc71b5e65)

Tasks on Time Ruler, showing the incomplete task that does not have the #temp tag:
![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/13829537/7edd7924-732b-491c-890c-2efbebbf3a59)

### Is it looking for dataview query language? 

```dataview
TASK
WHERE contains(tags, "#temp")
```

Variations I tried:
```TASK WHERE contains(tags, "#temp")```
```WHERE contains(tags, "#temp")```
```contains(tags, "#temp")```
```tags, "#temp"```

...What in the world is it looking for?

EDIT: My current understanding is that it's looking for dataviewJS arguments that can be placed within the brackets of dv.pages() only.

Thanks again for putting up with my massive bug reports. Let me know if any more information would be helpful.

**Comment by joshuatazrein** [comment]
I think this will be fixed by updating the docs to clarify this. I can also work in an error notification if the query is invalid.

For context, Time Ruler plugs the custom filter into: `dv.pages(<your custom filter>)['file']['tasks']`. I'll try throwing some stuff at it.
Settings only update when Time Ruler is reloaded, it says that at the bottom.

The upcoming version will update this documentation.

**Comment by joshuatazrein** [comment]
Added task filter in `1.2.0`
