### ISSUE TITLE
Scheduling task strips custom status

### ISSUE THREAD

**Issue by technotherion** [joshuatazrein/obsidian-time-ruler#19]
When a custom status is used for a to do task (e.g. anything but - [ ]), the task status is stripped from the task. 

Here's two example custom statuses that I am currently utilizing. The frog is [F] and the stopwatch icon one is [T].

![dragging](https://i.imgur.com/c5tAcDw.gif)

This behavior is also the same is being pulled from the Unscheduled pane. 

Easily fixed by re-adding the custom status into the checkbox, but figured it would be worth pointing out. 

EDIT: Also please let me know if i am in any way being overbearing or too nitpicky in the method/frequency of opening issues and/or requests.

**Comment by joshuatazrein** [comment]
Super grateful for these bug reports! Yes I can fix that in the upcoming release.
