### ISSUE TITLE
This plugin's suggestion for Tasks format of times will break user's Start and Due dates in Tasks

### ISSUE THREAD

**Issue by claremacrae** [joshuatazrein/obsidian-time-ruler#2]
Hi, this plugin looks amazing and I am really looking forward to trying it out, when I have a break in working on Tasks. I took over as its maintainer and author a year ago.

Please can you change this in your docs:

> Tasks: ⏳ yyyy-mm-dd [startTime:: hh-mm] 📅 yyyy-mm-dd [length:: #h#m] ⏬/🔽/🔼/⏫/

To this (without any accidental double spaces)

> Tasks: [startTime:: hh-mm][length:: #h#m] ⏳ yyyy-mm-dd  📅 yyyy-mm-dd  ⏬/🔽/🔼/⏫/

The reason is this current limitation in Tasks parsing:

https://publish.obsidian.md/tasks/Getting+Started/Auto-Suggest#What%20do%20I%20need%20to%20know%20about%20the%20order%20of%20items%20in%20a%20task?

> **WARNING**
> Mixing any descriptive text in amongst the emojis and their values **will cause emojis before the descriptive text to not be recognised by Tasks, and not be searchable**.

We will make Tasks more forgiving at some point, but it's a non-trivial task, and not currently at the top of the priority list, hence this request.

Thanks and best wishes for this valuable plugin!

**Comment by joshuatazrein** [comment]
Thanks very much, Tasks is a great plugin! I will update the docs to match this.
