### ISSUE TITLE
[FR] Reminder freature or Obsidian-Reminder integration

### ISSUE THREAD

**Issue by technotherion** [joshuatazrein/obsidian-time-ruler#20]
**Is your feature request related to a problem? Please describe.**
Obsidian-Reminder is compatible with Time Ruler, but I find that there could be further seamless integration. 
**Describe the solution you'd like**
Obsidian Reminders uses the task format ⏱️Time in order to set reminders. Currently, if reminders are set on a task on Time Ruler, the reminder time shows as well: 
![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/13829537/ffff71f7-f749-44a2-bc07-9ebbc100ed4a)

Another format the plugin uses is (@Time). 

I feel that you could create your own reminder system within Time Ruler quite well, but I think that's a lot to ask of someone!!

Ideas: 
- Stopwatch icon that shows up on scheduled task hover, upon clicking adds a reminder time to the task based on its startTime that can be further configured

This is totally me throwing something at the wall and seeing if it sticks. If you don't like the idea then don't worry :P

**Comment by joshuatazrein** [comment]
I could probably support formatting reminders in tasks, which wouldn't be too hard. Perhaps in future I'll add a "reminder" and "deadline" drag option, that would be cool. 

Thanks for the suggestion, added these to the changelog!

**Comment by joshuatazrein** [comment]
`1.0.5` adds support for reminders.
