### ISSUE TITLE
allow simple HH:MM-HH:MM at start of description for times

### ISSUE THREAD

**Issue by pcause** [joshuatazrein/obsidian-time-ruler#21]
**Is your feature request related to a problem? Please describe.**
using the syntax specified for tasks involved a bunch of extra type.  can he have something simpler?  

**Describe the solution you'd like**
If the first thing in a task description is of the form - HH:MM-HH:MM use the two times as start/end.

**Describe alternatives you've considered**
Using the options you've described

**Comment by joshuatazrein** [comment]
This seems fine, and would be nice and simple. I could add a "simple" formatting option for people who want to skip inline fields. However, if you want to skip the extra typing I would recommend installing the "Tasks" plugin and using the command "Tasks: Create or Edit Task" to insert metadata.

**Comment by pcause** [comment]
I do use the tasks plugin and thanks for adding to the roadmap.

**Comment by joshuatazrein** [comment]
This will be in the upcoming release.
