### ISSUE TITLE
Broken time ruler view

### ISSUE THREAD

**Issue by eduongAZ** [joshuatazrein/obsidian-time-ruler#22]
**Describe the bug**
Unlike the views shown on GitHub README with the date timeline displayed horizontally, my view displays the date vertically, buttons do not align, and there is no time ruler.

**To Reproduce**
1. Create a new Obsidian vault
2. Install Dataview and Time Ruler plugins

**Expected behavior**
The views shown on GitHub README with the date timeline displayed horizontally and the time ruler shown vertically.

**Screenshots**

How the view should look
<img width="855" alt="Screenshot 2023-08-06 at 9 12 58 AM" src="https://github.com/joshuatazrein/obsidian-time-ruler/assets/86935179/230af56c-79ac-408a-83d0-d38e26e91355">

How my view looks
<img width="575" alt="Screenshot 2023-08-06 at 9 14 12 AM" src="https://github.com/joshuatazrein/obsidian-time-ruler/assets/86935179/1fb33ed5-0935-4ea8-8cb4-5c6f449422bb">

**Obsidian Version:** 
- [ ] Mac Desktop

**Additional context**
This is tested on a new obsidian vault, no theme, no other plugins other than Dataview and Time Ruler.

**Comment by joshuatazrein** [comment]
That's very strange. Let me try to reproduce the issue.

**Comment by joshuatazrein** [comment]
I just tried on a vault with only those two plugins installed and it looks correct. In order to fix this can you send me the test vault in question? Upload it as a `.zip`. Thanks!

<img width="1386" alt="Screenshot 2023-08-06 at 11 13 10 AM" src="https://github.com/joshuatazrein/obsidian-time-ruler/assets/84872947/e97f637e-1a2d-45a9-a708-c0d2543b11e2">

**Comment by eduongAZ** [comment]
[test-task-vault.zip](https://github.com/joshuatazrein/obsidian-time-ruler/files/12270218/test-task-vault.zip)

Hi Joshua!

Thank you for looking into this. I really want to try out your plugin.

**Comment by joshuatazrein** [comment]
Ok, it's just an oversight where `styles.css` isn't included. Let me update the release.
