### ISSUE TITLE
Unable to update to v 1.0.5

### ISSUE THREAD

**Issue by elvarb** [joshuatazrein/obsidian-time-ruler#23]
**Describe the bug**
Unable to update to v 1.0.5, installed version is 1.0.4, same behaviors in two vaults, both on Windows and Linux

**To Reproduce**
1. Install the plugin
2. Go to update
3. Dialog comes up that it is installing
4. Seems to finish but installed version is still 1.0.4, pressing check for update prompts that an update is available

**Expected behavior**
Should update to 1.0.5 automatically

**Obsidian Version:** 
- [ ] Mobile
- [x] Desktop

**Comment by MSBack** [comment]
Same here. I think there is some mismatch in the manifest, perhaps?

**Comment by MSBack** [comment]
Yeah, the manifest of 1.0.5 says version 1.0.4. So you actually have the latest version, but it is confusing Obsidian by having the wrong version number in the manifest.

**Comment by MSBack** [comment]
I manually edited the manifest file to get rid of the incorrect update notification.

**Comment by joshuatazrein** [comment]
Thanks for catching this, I have fixed! Try updating now. There might be a delay in Obsidian so if it's not updated yet, just update the manifest directly. The code & styles should be correct.
