### ISSUE TITLE
Drag and drop tasks using the day view doesn't work

### ISSUE THREAD

**Issue by elvarb** [joshuatazrein/obsidian-time-ruler#24]
**Is your feature request related to a problem? Please describe.**
As someone who does not need to assign tasks to a specific time during the day I want to use the day view.

When trying to drag a task to a different day nothing happens.

**Describe the solution you'd like**
Dragging tasks should work the same if its dropped on a day as it is when dropped to the per hour timeline

**Comment by joshuatazrein** [comment]
In order to change the task, you can drag to specific targets:
- the date heading
- the date button (above)
- any timeblock's heading in the date

**Comment by joshuatazrein** [comment]
In `1.1.0` drop targets are larger.
