### ISSUE TITLE
Support show/hide completed & other custom-status in calendar/list view

### ISSUE THREAD

**Issue by yoghurtdewdew** [joshuatazrein/obsidian-time-ruler#25]
**Is your feature request related to a problem? Please describe.**
See here https://github.com/joshuatazrein/obsidian-time-ruler/issues/26

**Describe the solution you'd like**

This plugin is simply too convenient. It can display all tasks without `- [x]` state listing just on one page or in a perfect calendar view. However, I frequently use custom checkbox formats and hope to review the completed and things in customized status in this plugin. Therefore, I really hope to have other review functions besides unscheduled, to review completed and customized status content, and hope they will listing just on one page or in a perfect calendar view as well. 

**Describe alternatives you've considered**
No alternatives except searching (dataview seemed to be slow with no calendar view and I didn't learn about how to use it)

**Additional context**

**Comment by joshuatazrein** [comment]
Custom checkboxes are supported in Settings, I can add a dropdown to filter for custom statuses.

Time Ruler doesn't display completed tasks, but I can make it so if `x` is included in custom statuses it will do this.

**Comment by yoghurtdewdew** [comment]
Thanks for your great work! I may not described clearly. 

I saw the options to exclude/include custom statuses, but there only alow one setting. 

And, if there will be buttons just like "unschedule" to check each statuses groups, that will be so much easier to filter out todos with different custom statuses to check them group by group.

<img width="730" alt="image" src="https://github.com/joshuatazrein/obsidian-time-ruler/assets/63794438/c5831cdb-17f8-4c44-935b-8f2dc3291a8f">
