### ISSUE TITLE
Support emoji & custom checkbox

### ISSUE THREAD

**Issue by yoghurtdewdew** [joshuatazrein/obsidian-time-ruler#26]
**Describe the bug**

I use emoji and custom checkbox frequently for todos, it seemed that they won't appear correctly. 

**To Reproduce**

As you can see in this:

![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/63794438/2a213379-9852-4f54-8d88-0c933855ba8b)

**Expected behavior**
Support emoji & custom checkbox

**Screenshots**

**Obsidian Version:** 
Desktop 1.3.7 with time-ruler 1.0.5 (newest)

**Additional context**

see here https://github.com/joshuatazrein/obsidian-time-ruler/issues/25

**Comment by joshuatazrein** [comment]
Interesting, I can try to support emojis & custom status.

**Comment by joshuatazrein** [comment]
Filtering by custom statuses is in the upcoming release.

**Comment by yoghurtdewdew** [comment]
<img width="501" alt="image" src="https://github.com/joshuatazrein/obsidian-time-ruler/assets/63794438/cc8184e7-fe9f-4fa1-896f-28e7b3cd1892">

Thanks for your awesome creativity!

I just tried this!  

It showed nice characters with checkbox! 🥰

But the emojis still goes wrong. 😨
