### ISSUE TITLE
Day Planner format shows invalid time on timeline if hour is not two digits

### ISSUE THREAD

**Issue by technotherion** [joshuatazrein/obsidian-time-ruler#27]
In Time Ruler, any hours  in the single digits (e.g. 1:00 - 9:00) show as "invalid date" unless they are made to be two digits (e.g. 01:00 - 09:00). This invalid date appeared after 12:00 on the timeline but the behavior was inconsistent. At one point it appeared after 7PM on the timeline instead. These show correctly in Day Planner at 1AM. 

![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/13829537/fe3ccf81-e427-4a15-9bb9-1322b3b2bb20)

This is how it appears on day planner: 
![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/13829537/a72dc045-7edd-4c70-8980-7dd4b5c4d8a2)

**Comment by joshuatazrein** [comment]
For now, keep it as `HH:mm - HH:mm`. I'll update it to parse single digits as well.

**Comment by joshuatazrein** [comment]
This will be in the upcoming release.

**Comment by joshuatazrein** [comment]
Supported in `1.2.0`
