### ISSUE TITLE
Question/Bug? Are custom status emoji intended to show on timeline?

### ISSUE THREAD

**Issue by technotherion** [joshuatazrein/obsidian-time-ruler#28]
Tasks 4.5.0
Time Ruler 1.1.0
Style Settings
Minimal theme
Using ITS theme's S Checkboxes CSS

Here's an example of some of the tasks on Time Ruler's timeline vs in my notes:

![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/13829537/ce852c1a-0227-447f-88c5-2ffda8d04c8b)

![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/13829537/b8c512a3-fe36-47f9-94ad-87b1db946845)

The tasks do represent the correct status symbol, but the icons/emojis do not show. I do not know if this is intended or not.

**Comment by joshuatazrein** [comment]
It is intended currently; it's some extra work to fully integrate Custom Status emoji as I would have to parse the stylesheets and replace them accordingly. I'll check this out and will support it in future.

**Comment by joshuatazrein** [comment]
Unfortunately, I can't support default styling of custom statuses, because most themes only support those styles in the Obsidian editor. However, you can add your own custom status styles in the upcoming release.
