### ISSUE TITLE
Can't see and use the "Buttons" on GUI

### ISSUE THREAD

**Issue by Jeromandres** [joshuatazrein/obsidian-time-ruler#29]
**Describe the bug**
Can't see the "Buttons" on GUI
Impossible to Refresh, Search, Move from/ to Daily view

**To Reproduce**
- Clicking on "..." does not show any list of buttons -- neither left, middile or right clicks
- Buttons never appearing

**Screenshots**
![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/44743048/b01c20fc-c8af-4ff8-b487-7c98a0ee089f)

**Obsidian Version:** 
- 1.4.3 Desktop

**Additional context**
N/A

**Comment by joshuatazrein** [comment]
The Buttons shows up when you hover over it. I can't seem to reproduce it. Are you using a custom theme?

**Comment by Jeromandres** [comment]
Nope, Default theme

**Comment by Jeromandres** [comment]
Hi Joshua

If that helps, I use a Windows PC

Are you using a display feature of Obsidian, used in other functions or plugins -- to check if I can reproduce the issue on my set-up?

Last, any alternative way to access the features made accessible through "buttons" ?

Thx

**Comment by joshuatazrein** [comment]
No, it's just a hover modal. I can add some commands if it's not working (reload, toggle view)

**Comment by Jeromandres** [comment]
Here you go

Not sure how it may help

https://github.com/joshuatazrein/obsidian-time-ruler/assets/44743048/e91b6fb1-b2b9-4c35-96e3-91e19d483139
