### ISSUE TITLE
Support Custom Statuses

### ISSUE THREAD

**Issue by aventuraviper** [joshuatazrein/obsidian-time-ruler#3]
I love the idea of this plugin I would consider implementing it in my vault, which could help me replace a few external tools, however without support for [custom statuses](https://publish.obsidian.md/tasks/Getting+Started/Statuses/Custom+Statuses) I am left with multiple unscheduled "tasks" that aren't actually tasks.

I realise the plugin is earlier stages but wanted to highlight this and maybe open discussion on how to implement. Personally, adding a list of statuses to ignore in settings could work and/or ability to filter them live in the plugin.

**Comment by gypsyav** [comment]
I'm going to chime in here as well. I have a checklist I use for meetings that isn't a list of tasks and would love to be able to exclude it from the view. I'd also like to be able to exclude anything that's in my template folder.

**Comment by joshuatazrein** [comment]
Thanks for this discussion! The Tasks plugin supports a custom filter, where only tasks from a certain folder or tag are implemented. I'll update plugin with a setting to customize the Dataview search.

**Comment by joshuatazrein** [comment]
There is now a setting to choose a custom Dataview search passed to dv.pages(). This will filter the tasks used in the search, so you can filter out a specific folder or tag (document-level). 

Currently, no task which isn't listed as open `- [ ]` should show up in the plugin. Dataview tasks don't support custom statuses, so this might require a bit of massaging with regards to the [Dataview tasks search](https://blacksmithgu.github.io/obsidian-dataview/queries/query-types/#task).

**Comment by charle36** [comment]
Thanks for the plugin!

Canceled tasks ([-]) show up in the plugin. I tried to play with the settings to solve the issue, but nothing seems to work.

**Comment by joshuatazrein** [comment]
Thanks for mentioning this! The [latest release](https://github.com/joshuatazrein/obsidian-time-ruler/releases/tag/1.0.1) now supports custom statuses, excluding canceled tasks by default. You can download it directly from there, and just replace the files in the current plugin folder (.obsidian/plugins/obsidian-time-ruler).

**Comment by charle36** [comment]
Seems to work perfrectly, thanks!
