### ISSUE TITLE
Calendar hourly scales along default locals (e.g. 13:00 to 23:00) + start-end of day

### ISSUE THREAD

**Issue by Jeromandres** [joshuatazrein/obsidian-time-ruler#30]
**Is your feature request related to a problem? Please describe.**

- Hourly references are not intuitive, esp. for folks used to write e.g. 13:00 in afternoon
- Seemingly, others may wish to see e.g. 1pm
- Last I feel strange to have calendar starting at midnight -- it would be nice to be able to select in settings start and end default time for each day
- Of course display meant to be modified if a scheduled task/ event is before or after default timings

**Describe the solution you'd like**
- See above

**Describe alternatives you've considered**
- Priority-wise, follow locals

**Additional context**
N/A

**Comment by joshuatazrein** [comment]
Thanks for the feature request! This seems like a good feature to add. I've put it in the roadmap.

**Comment by joshuatazrein** [comment]
Supported in `1.2.0.`
