### ISSUE TITLE
Compatibility of task rescheduling with blockid

### ISSUE THREAD

**Issue by Jeromandres** [joshuatazrein/obsidian-time-ruler#32]
** Context of use**
I am setting blockid to tasks to be able to create links to the the given tasks.
I use it to pull linked to tasks within a Kanban, and be able to move tasks (links to tasks indeed) between columns

Please refer to https://help.obsidian.md/Linking+notes+and+files/Internal+links#Link+to+a+block+in+a+note.
Reference to blocks are automatically created with a alphanumerical index prefixed by caret (^)

**Describe the bug**
When a scheduled task is moved from one timing to another, the ending block id (^followed by a reference given by Obsidian) is moved backward in the sequence of data in the task line. This breaks the links to the block, as the reference shall be ending the block, which is not the case in the current implementation of TimeRuler I guess.

**To Reproduce**
1. Create a reference to a task (to the one-line block consisting in the task)
2. Set a Scheduled Date and Starting Time for the task
3. Launch command: Copy Block Link: Copy embed to current block or heading -- this creates the reference (caret followed by Obsidian given alphanumerical code)
4. Paste the link to the task (one-line block indeed) wherever you want
5. Reschedule the task in Time Ruler to another timing and/ or day
6. Come back to the pasted task embedded link
7. See it broken

Nota:
- in the task full line, you can see the reference (caret followed by alphanum code) is no more latest on line.
- if you move the "caret followed by alphanum code" to the end of the task/ one line block -- ensuring there is no black space after the block reference -- the pasted link is restored 
- It is cumbersome to have to clean up the task line at each rescheduling

**Expected behavior**
Keep block reference unchanged in tasks(events likely though not tested), by letting it at end of task/ event, without ending spaces

**Obsidian Version:** 
- 1.4.6 Windows Desktop

**Additional context**

**Comment by joshuatazrein** [comment]
Thanks for the issue, I'll add support for block formatting soon.

**Comment by joshuatazrein** [comment]
Block references are supported in `1.2.0`
