### ISSUE TITLE
Plugin breaks obsidian when used

### ISSUE THREAD

**Issue by endlessblink** [joshuatazrein/obsidian-time-ruler#33]
**Describe the bug**

The plugin breaks when trying to use it in Obsidian.

**To Reproduce**
Just click on the shortcut to use it. 

**Screenshots**
![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/37155282/987a0ac1-de5a-4f60-967a-c31ed18214cb)

**Obsidian Version:** 
- [ ] Desktop

**Comment by joshuatazrein** [comment]
- The first picture is the result of an error being thrown. Can you show the console log when that blank screen issue happens?
- The second picture seems to be the result of a theme reducing pane sizes in the sidebar. If you want it to be big drag it to a different pane or use a different theme.
