### ISSUE TITLE
Add support for CalDAV calendars

### ISSUE THREAD

**Issue by galsom** [joshuatazrein/obsidian-time-ruler#34]
**Is your feature request related to a problem? Please describe.**
Most of the calendars I work with are CalDAV based and require a username and password to authenticate, which is not yet supported by this very promising add-on.

**Describe the solution you'd like**
Would it be possible to support CalDAV based calendars as well? E.g. Full Calendar does support them, but it would be nice to have this directly in Time Ruler as well.

**Describe alternatives you've considered**
Use the CalDAV support from Full Calendar, but these events do not appear to show up in Time Ruler if they originate from a CalDAV calendar in Full Calendar.

**Additional context**
Hope this is feasible to add.

**Comment by joshuatazrein** [comment]
This would be good to add, I'll look into it and see if it's feasible. Added to "considering"
