### ISSUE TITLE
Time ruler Crashes Obsidian

### ISSUE THREAD

**Issue by endlessblink** [joshuatazrein/obsidian-time-ruler#35]
**Describe the bug**
After performing several tasks in Time ruler (like dragging tasks or crossing them off), Obsidian crashes.

**Screenshots**
![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/37155282/a2b7eb06-0217-47e3-9110-17c90d5b1a1d)

**Obsidian Version:** 

- [V1.4.4 ] Desktop

**Comment by joshuatazrein** [comment]
There are a lot of errors with FullCalendar and Supercharged Links. Turn those off then try again.

**Comment by joshuatazrein** [comment]
Closing this issue until further information is added
