### ISSUE TITLE
click task when note open/pinned causes extra open tab for note

### ISSUE THREAD

**Issue by pcause** [joshuatazrein/obsidian-time-ruler#36]
**Describe the bug**
If I click a task and the note the task is located in is already open in a pinned tab the note is opened again in a new tab.

**To Reproduce**
Pin a note with a task that is displayed in the time ruler.  click the task in time ruler.  new tab will open for that page

**Expected behavior**
Switches to existing open note that task in in

- [ ] Mobile
- [ x] Desktop 1.4.5

**Comment by joshuatazrein** [comment]
This is the internal Obsidian API's default setting: the plugin treats the task as if you clicked on a Markdown link. I don't think I can change this behavior.
