### ISSUE TITLE
problem with length and item not appearing in time line

### ISSUE THREAD

**Issue by pcause** [joshuatazrein/obsidian-time-ruler#38]
**Describe the bug**
I have selected to use task format.  I have a task:

- [ ] [startTime:: 19-00]  [length:: 1h] a start time 📅 2023-09-01 

this is shown in the timeline view as unscheduled (tasks at the top, and isn't shown in the time ruler.  But you can see it has a 1h next to the task 

![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/1071479/f4f078c6-cef8-4444-abaf-787fcf3ae93c)

Note that entering [length:: 1 hour] gives the same behavior.

This is entered as the example for using tasks.  I think the README is ambiguous especially about the length.  what the heckis #h#m?  dataview docs uses "1 hour" or "1 hour 5 minutes"

Other information: I have an ics calendar also included.  The item from there shows up in the ruler.  I can't seem to get any items I create to appear on the ruler.  I am likely doing something wrong, but am using the example you provided for the start and length and the tasks due date.

**To Reproduce**

create the task above

**Expected behavior**

Item would show up in the time ruler.

**Obsidian Version:** 
- [ ] Mobile
- [x ] Desktop 1.4.5

**Comment by joshuatazrein** [comment]
The format is incorrect.

- `[startTime: 19:00]` needs a colon
- the calendar emoji is for due dates, not start dates

**Comment by pcause** [comment]
thanks.  the readme isn't clear that you needed a scheduled.  i think it is common to have a due without a scheduled.  perhaps if there is a due and no scheduled you use the due as scheduled.

**Comment by joshuatazrein** [comment]
You can have due without scheduled, it just inserts it as a due date:
<img width="472" alt="Screenshot 2023-09-02 at 2 54 40 PM" src="https://github.com/joshuatazrein/obsidian-time-ruler/assets/84872947/47f30ea0-e686-4d5a-b885-1b31c35ca2ba">
