### ISSUE TITLE
make clicking on item open note and position on line

### ISSUE THREAD

**Issue by pcause** [joshuatazrein/obsidian-time-ruler#39]
**Is your feature request related to a problem? Please describe.**

The the time ruler, when I click on a task at the top, which are unscheduled it will open the note containing the task but it won't position the cursor to the line with the task.  

**Describe the solution you'd like**

The dataview task metadata includes the line number for the file.  use that to open the note at the line where the task is present.

**Comment by joshuatazrein** [comment]
Clicking on tasks already navigates to the task itself. Clicking on headings navigates to the file, or heading in question. 

If this isn't working for you, please send a screen recording.
