### ISSUE TITLE
Tags stripped from task description if task is moved

### ISSUE THREAD

**Issue by gypsyav** [joshuatazrein/obsidian-time-ruler#4]
I love the concept of this plugin and tried it out in my vault only to run into a problem when it came to moving tasks. When I drag and drop a task it strips the task of any tags I had in the description. This causes a break in my workflow I can't work around without readding the tags I had. Which means making note of any tags before moving the task so I don't miss anything, then retyping them in the task after it is moved.

Thanks for the work you've already put into this.

**Comment by joshuatazrein** [comment]
Thanks for this issue! I believe it should be fixed. Let me know if this is not the case.

**Comment by joshuatazrein** [comment]
Tags will now be kept in the task and inserted before any inline fields. Thanks for catching this issue!
