### ISSUE TITLE
support using due date not just scheduled date

### ISSUE THREAD

**Issue by pcause** [joshuatazrein/obsidian-time-ruler#40]
**Is your feature request related to a problem? Please describe.**
In tasks, a recurring task must have a due date.  If the task is to be done and is also due on a specific date, I need to enter the date twice.  A

**Describe the solution you'd like**
If there is a due date and no scheduled date use the due date to place on the time ruler.  If both exists use the scheduled date.

**Describe alternatives you've considered**
I'd thought I could use just scheduled, but that breaks the recurring tasks.  

**Additional context**

A more advanced implementation would be to have an item on the calendar every day from scheduled to due date at the specified time.  You might color them differently with css.

**Comment by joshuatazrein** [comment]
There is due date support which places tasks on the Time Ruler, they show up in the all-day view as links until the official due date. Can you clarify what you mean here?

**Comment by pcause** [comment]
OK, now I understand the display better.   here is what I suggest:

For an item with a due and no scheduled date:

- only show the item on the due date.  if it has a startTime show in the ruler, otherwise in all day.
- if not done, show in all day, after the due date, even if there is a startTime.

For items with a scheduled and a due date:

- show initially on scheduled date in ruler is there is a startTime, otherwise in all day
- between scheduled and due, show in all day
- on due show in the ruler is there is a startTime, otherwise in all day
- if not completed on the due date, show in all day until completed.
-

**Comment by pcause** [comment]
If only a scheduled date:

- show in ruler in the scheduled date if a startTime is specified, otherwise in all day
-  if not completed on the scheduled date, after the scheduled date, show in all day until completed

**Comment by joshuatazrein** [comment]
Those are both current features.

**Comment by pcause** [comment]
Thanks.  Your plugin so it should work the way you think makes sense.  I'll see if I can live with this but am not sure.  This is an excellent plugin in any case and thanks for making it and for being so responsive

**Comment by joshuatazrein** [comment]
No problem! Thanks for offering feedback, I'm always looking to improve usability. I think it would help if you could provide a diagram or drawing of your suggested layout here so I can be more clear on what is missing.
