### ISSUE TITLE
[FR] Timer sounds 

### ISSUE THREAD

**Issue by technotherion** [joshuatazrein/obsidian-time-ruler#43]
It would be helpful to have a sound that goes off when the timer has elapsed or when a reminder goes off, and to maybe even have these sounds be customized. 
I'm currently using SnapTimer outside of Obsidian, which also has a ticking option while the timer is running that I quite enjoy.
Additionally, having an option to change the 'task complete' noise to something customizable could be a nice feature.
None of these are things I see as very important at all.

**Comment by joshuatazrein** [comment]
Ok I can add these to the changelog
