### ISSUE TITLE
make split between all day and time ruler moveable

### ISSUE THREAD

**Issue by pcause** [joshuatazrein/obsidian-time-ruler#45]
**Is your feature request related to a problem? Please describe.**
Seems that the split of space between the ruler and the all day items is fixed.  I want to set the split to be relevant to what I am doing and feel I need.  Varies depending on day, # of all day items, etc.

See above

** A clear and concise description of what you want to happen.

Be able to drag the divider up/down to change the sizes of the all day and ruler displays.

**Describe alternatives you've considered**

seeing if I can do this with css.  think i might be able but haven't figured out yet.

**Additional context**

**Comment by joshuatazrein** [comment]
That would be nice. I'll add it to the roadmap.
