### ISSUE TITLE
option to show items with only a due date and no times only on the date the item is due

### ISSUE THREAD

**Issue by pcause** [joshuatazrein/obsidian-time-ruler#46]
**Is your feature request related to a problem? Please describe.**

I have items with just a due date in tasks.  I don't want them to appear in "all day", other than the day they were due.

**Describe the solution you'd like**
An option is settings to, "Show due date only tasks only on due date" and then show those items in all day only on the due date.

**Describe alternatives you've considered**

Going through vault and manually editing lots of tasks.

**Additional context**

A lot of folks only use a due date for scheduling.  if you were a todo.txt fan it only had due date.

**Comment by joshuatazrein** [comment]
I would suggest just using the scheduled date, since that is the intended function. Are there other plugins that you use which would conflict with that?

**Comment by pcause** [comment]
I, and I suspect others, have tasks created before this plugin and going though and changing everything is tedious.   Also,many systems of managing todos use a start date and then a due date.  in these you don't want to see due before you are starting.  you used scheduled to mean what other systems use as start.

lastly, tasks plugin has 3 dates.  people use the 3 in different ways depending what system they use or what they find convenient.  i think flexibility to let the user decide how to use dates would make the plugin more widely /easily adopted.  I would suggest the following if the chosen format is  "tasks":


- show due only on due date (default no)
- use start in time-ruler as well as scheduled (default no)

You get default behavior by doing notching.  But now a user can have a start time on the calendar (when to start work), a scheduled time (when planned to be done), and due time  (when MUST be done).    I would also show due in the all day from the earliest of start/scheduled through completed.

if you follow the tasks discussion on discord you'll see there are a wide variety of systems and approaches.  That is my personal experience and having worked on a plugin to another product to add tasks a decade ago what I learned over a few years supporting the plugin. 

if you want to limit this to just scheduled, no problem.  It is your effort and it should work the way you want it to,.  I think this is an excellent piece of work and think by making a few changes it could be more widely adopted.  Just my opinion.

**Comment by joshuatazrein** [comment]
Thanks for explaining the Tasks system more. It would probably be pretty easy to just reconfigure the parser to accept due dates (or even a custom key) as scheduled dates and cut out the "due" property, which would be a much simpler form of task management. I haven't incorporated "start" much, either, just hiding the task from the search if start isn't there yet. I'll look further into the Tasks plugin and see if I can expand the integration there with different systems.

**Comment by pcause** [comment]
Yes.  I think that any item not completed (or excluded characters) that has a scheduled date appears on the date.  If it has a time, it appears in the ruler otherwise the all day.  Things with no date and no time appear in all day.  That would leave people free to use whatever system they chose.

I assume that once an item is triggered by date and time it would remain in that slot in the ruler until completed.  If it has a date and no time and is not completed it stays in all day until completed.

One last idea.  You might have the items have a different css so that a user can color a start, schedued and due item as they choose.  You could just use the css class that Tasks usr, as a lot of folks have done work on stylizing Tasks using its css.

**Comment by joshuatazrein** [comment]
That's a great idea too. I'll add that to Changelog as well.
