### ISSUE TITLE
Easier way to discern overlapping tasks

### ISSUE THREAD

**Issue by Suyashtnt** [joshuatazrein/obsidian-time-ruler#47]
**Is your feature request related to a problem? Please describe.**

See the following
![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/45307955/47c3efa4-ef20-4b75-a42d-1ec4f77d4157)
The current format makes it difficult to tell that `Take out the trash` overlaps with `Take out the garbog`

**Describe the solution you'd like**
Some easier way to see overlapping events. Maybe Differenciating colours or an indent to see what overlaps what

**Describe alternatives you've considered**
Using full calendar events over tasks, but thats less flexible in terms of where I can store the tasks

**Additional context**
None

**Comment by joshuatazrein** [comment]
I can add this to the roadmap, this wouldn't be too hard
