### ISSUE TITLE
having the time ruler open slows down Onsidian significantly

### ISSUE THREAD

**Issue by pcause** [joshuatazrein/obsidian-time-ruler#48]
**Describe the bug**

If I have time ruler open, Obsidian slows down significantly.  

**To Reproduce**
- Open a note
- Close the note
- Open time ruler
- Open the same note from above

**Expected behavior**

When I open the note without time ruler open the note opens in a second. After opening time ruler it can take 5-10 seconds to open.  The note being opened has no tasks.  I do not change the tasks between the times I open the note.  I've tried waiting 10-15 seconds after opening time ruler in case there is some async activity.  It makes no difference

I see other sluggishness as well in Obsidian when the ruler is open.

**Obsidian Version:** 
- [ ] Mobile
- [x ] Desktop 1.4.6

**Additional context**

Just closed and reopened obsidian.  The delay is very small now.  Guess not clear if it is Obsidian or time ruler.

**Comment by joshuatazrein** [comment]
It is probably some of both. I can work on optimizing performance as it's probably an issue with the metadata changing.
