### ISSUE TITLE
Move flexible Page selection

### ISSUE THREAD

**Issue by rapatel0** [joshuatazrein/obsidian-time-ruler#49]
**Is your feature request related to a problem? Please describe.**
`dv.pages('<custom_filter')` is quite limited. I have other fields called status that indicate whether a page should be ignored or not. 

**Describe the solution you'd like**
If we could pass a dataview page object that would be preferable. 

Example;
```javascript
// Instead of this:
dv.pages('<custom_filter>') 

// This 
dv.pages('<partial_custom_filter>').where(p=>p.status.contains('InProgress') | p.status.contains('To Do'))
```
In other words, it would be better if we could just pass the whole `dv.pages()...` object as a parameter. Alternatively, if we could pass a dataview query string.

**Comment by joshuatazrein** [comment]
I mean, I could just enable custom JavaScript for filtering. I think that's the most customizable for Dataview people. Added to changelog.
