### ISSUE TITLE
recurring items in ics calendar (not about recurring obsidian tasks)

### ISSUE THREAD

**Issue by pcause** [joshuatazrein/obsidian-time-ruler#50]
**Describe the bug**
The recurring items in my ics calendar are not being displayed in the time ruler.  Is this known and planned for future?

**To Reproduce**
1) have a calendar with recurring items.  Try something that is daily first
2) get the ics link
3) add to the settings

**Expected behavior**
I expect to see a recurring ics item appear on each day it would appear in the native system's calendar.

**Obsidian Version:** 
- [ ] Mobile
- [ x] Desktop 1.4.8

**Additional context**

If this isn't implemented yet you can look at the ICS plugin.  It is able to get events inclduing recurring.

**Comment by joshuatazrein** [comment]
Good catch, added to changelog.

**Comment by j-palindrome** [comment]
This has been added in v2.5.0.
