### ISSUE TITLE
24hr format in the ruler

### ISSUE THREAD

**Issue by negue** [joshuatazrein/obsidian-time-ruler#51]
**Is your feature request related to a problem? Please describe.**
Currently the ruler shows two times the 12hr parts, which is a bit "off" for countries that don't use the AM/PM ^^

**Describe the solution you'd like**
I'd like to have the 2nd ruler going from 13 till 24.

**Describe alternatives you've considered**

**Additional context**

**Comment by joshuatazrein** [comment]
Makes sense. I'll add in the next release.
