### ISSUE TITLE
Open Ruler in Main Tabs instead of Sidebar

### ISSUE THREAD

**Issue by negue** [joshuatazrein/obsidian-time-ruler#52]
**Is your feature request related to a problem? Please describe.**
Currently the ruler opens up in the sidebar. This is fine a one day view but for a bigger overview the main tabs are better.

**Describe the solution you'd like**
Maybe an option to choose what should happen when pressing the command icon.

**Describe alternatives you've considered**
I tried to move the panel to the main tabs but every other start of Obsidian the Panel stays empty, don't know if I can get the actual error from console if that happens

**Additional context**

**Comment by joshuatazrein** [comment]
Drag it to the main tab.
