### ISSUE TITLE
nothing displayed 1.4.11

### ISSUE THREAD

**Issue by pcause** [joshuatazrein/obsidian-time-ruler#53]
**Describe the bug**
I installed 1.4.11 (latest release) and none of my tasks are being displayed and the ics calendar is not being displayed.  I get nothing but a ruler.  

**To Reproduce**
- Install 1.4.11
- start obsidian
- open time ruler
- 
**Expected behavior**
To see the same tasks I see in my daily note.  Most of the tasks are recurring tasks.  The were there last week.

**Obsidian Version:** 
- [ ] Mobile
- [ x] Desktop 1.4.11

And, yes, did restart obsidian.  And I had installed the latest version of time ruler before 1.4.11 update

**Comment by pcause** [comment]
dataview updated this AM and I can now see the ics calendar events but not the obsidian tasks.

**Comment by joshuatazrein** [comment]
This is a strange issue. It's not happening anymore for me. Latest release is coming out today, let me know if it still happens.

**Comment by pcause** [comment]
the tasks appeared a few days later.  looks ok now.  weird as you changed nothing.  i know dataview got updated 2x while this was happening

**Comment by joshuatazrein** [comment]
Yeah I think it was related to Dataview and not specific to the plugin. Loading all those tasks is a big performance crunch. I'll be looking for ways to optimize.

**Comment by pcause** [comment]
yes, any memory/performance improvements are welcome

**Comment by robmikulec** [comment]
I think it may be related to recurring events?  When I add an ICS calendar it shows UNLESS the appointments are recurring, then they dont show.

**Comment by joshuatazrein** [comment]
Yes, I think that this is a bug with the underlying ical library so I will need to figure out how to rewrite it. Hope to support recurring events soon.
