### ISSUE TITLE
Day Planner Integration Broken

### ISSUE THREAD

**Issue by martydingo** [joshuatazrein/obsidian-time-ruler#54]
**Describe the bug**

**To Reproduce**
1. Install Time Ruler
2. Install new dayplanner https://github.com/ivan-lednev/obsidian-day-planner
3. Open Dev Console
4. Open Time Ruler, Observe Console Issues

**Expected behavior**
I expect to see the schedule in Time Ruler as created by Day Planner 

**Screenshots**

**Obsidian Version:** 
- [ ] Mobile
- [ x ] Desktop

**Additional context**
I believe this is because of the new configuration 0.7.0 day planner brought in, as this is erroring when investigating the `day-planner` configuration for `folder`, which no longer exists. 

```
TypeError: Cannot destructure property 'folder' of '(intermediate value)' as it is null.
    at getDailyNoteInfo (plugin:time-ruler:68330:11)
    at async setupStore (plugin:time-ruler:69979:27)
```

**Comment by gypsyav** [comment]
I was able to get the day planner integration to work by adding the date before the time. So 2023-09-15 12:00 - 13:00 shows at the correct time but 12:00 - 13:00 only shows up in an undated Day Planner section in Unscheduled.

**Comment by joshuatazrein** [comment]
Is this in a daily note? If you only add times to other files it won't work.

**Comment by gypsyav** [comment]
Yes, this is in the daily note. This is my file format for daily notes /Daily Notes/<YYYY>/<MM> - <MMM>/<YYYY-MM-DD DDD>.md

**Comment by joshuatazrein** [comment]
That's why. The format for daily notes is only available with a single folder and a single date format. For now just add in the daily note. I'll check the Day Planner settings to see what they do over there.

**Comment by gypsyav** [comment]
> That's why. The format for daily notes is only available with a single folder and a single date format. For now just add in the daily note. I'll check the Day Planner settings to see what they do over there.

I'm not sure what you mean by add in the daily note as that is what I was trying to do.  It is the note created by periodic notes. I changed the file name/folder in the periodic notes settings.

**Comment by joshuatazrein** [comment]
The [periodic notes](https://obsidian.md/plugins?id=periodic-notes) plugin, correct? That's not currently supported. Time Ruler parses the core Obsidian Daily Notes setting.

**Comment by martydingo** [comment]
Why is this closed? It's not working. I will raise an issue for support of Periodic Notes, as I require Monthly, Weekly & Daily notes but only need this to parse Daily Notes.

**Comment by joshuatazrein** [comment]
It's added to the roadmap, when I put things there I close issues.
