### ISSUE TITLE
Show completed task will show unscheduled tasks

### ISSUE THREAD

**Issue by SettingDust** [joshuatazrein/obsidian-time-ruler#57]
**Describe the bug**
The option to show completed task will show unscheduled tasks.

**Expected behavior**
 The unscheduled tasks should in unscheduled tab

**Screenshots**
![图片](https://github.com/joshuatazrein/obsidian-time-ruler/assets/19922286/36c1db1e-1a00-4651-b86e-fb5a185d4e63)

**Obsidian Version:** 
- [ ] Mobile
- [x] Desktop

**Additional context**

**Comment by joshuatazrein** [comment]
Fixed in upcoming release!
