### ISSUE TITLE
Error in processing task tags

### ISSUE THREAD

**Issue by Sotis-Oph** [joshuatazrein/obsidian-time-ruler#58]
**Bug description**
Tags written with non-Latin characters are not removed from the header.
And they are duplicated every time a task is moved or changed.

**Steps to reproduce the behavior:**
1. Create a task with a tag `Тест`
2. Move the task or change the duration
3. See error

**Expected behavior**
The header must be without tags and they shouldn't be duplicated

**Version:** 
- Obsidian Desktop - 1.4.13
- Time Ruler - 1.3.3

**Additional context**
The problem is in the regular expression `TAG_SEARCH = /#[\w-\/]+ */g` which does not take non-Latin characters into account.
It can be replaced by `TAG_SEARCH = /#[\p{Letter}\/\d_-]+/gu`
The variant is quite simple, but it fits better to what is described in obsidian documentation. 
https://help.obsidian.md/Editing+and+formatting/Tags#Tag+format

**Comment by joshuatazrein** [comment]
Changed the regex in upcoming release!
