### ISSUE TITLE
Gets rid of first number in a task when I use Tasks emoji format

### ISSUE THREAD

**Issue by gabmifre** [joshuatazrein/obsidian-time-ruler#59]
**Describe the bug**
I am using the Tasks plugin to format my tasks. When I have a task that starts with a number, e.g. "- [ ] 2 Title of the Chapter 📅 2023-09-26", the time ruler view does not display the first number and removes it when I move the task around to a time block in Time Ruler or check it off. It also happens if there is a decimal: 2.6 is treated as .6 . I think it treats it as a Day Planner format even though I told it to use Tasks format. I use a number because I have book chapters and sections and I don't want to write a non-numeral at the start of every task.

**To Reproduce**
1. Create a task starting with a number and a due date, e.g. "- [ ] 2 Title of the Chapter 📅 2023-09-26 "
2. Click on Time Ruler
3. Check off the task, or place it onto a time slot
4. Time Ruler uses a different format, not the Tasks format (I think it uses Day Planner format, which I have installed the plugin for, but I am using the Tasks emoji format) and deletes the first number in the task name

**Expected behavior**
I do not want the plugin to remove the first number in my tasks, or to ignore it in the Time Ruler weekly view given that I am using Tasks emoji format.

**Screenshots**

**Obsidian Version:** 
Desktop

**Additional context**
I paused Day Planner and I have told Time Ruler to use "Tasks" field format in settings, and still have this issue.

**Comment by joshuatazrein** [comment]
Time Ruler tries to detect the format of tasks, and parses tasks in every format. I can switch that setting in the upcoming release.
