### ISSUE TITLE
tag a new release after updates are made

### ISSUE THREAD

**Issue by pastorjack** [joshuatazrein/obsidian-time-ruler#6]
I use BRAT to add and update plugins that are not on the official repository. If you tag a new release after updating the code, then it will allow me to automatically update.

Thanks!

**Comment by joshuatazrein** [comment]
Thanks—I will definitely do so but am waiting until the plugin gets added to the official repo to move on from 1.0.0 (it has been awaiting review for 3 weeks). Sorry about the delay, I certainly hope it will be added to the official repo soon! For now I will post a notification here on each regular update.

**Comment by joshuatazrein** [comment]
New release! Calendar view. Binaries are updated!

**Comment by joshuatazrein** [comment]
Happy to say the plugin is now an official Obsidian plugin! So updates will now come in that way.
