### ISSUE TITLE
[Question] Can't update to version >1.3.1

### ISSUE THREAD

**Issue by SettingDust** [joshuatazrein/obsidian-time-ruler#60]
The obsidian always shows that the newest is 1.3.1. What's cloud be the reason?
![图片](https://github.com/joshuatazrein/obsidian-time-ruler/assets/19922286/3866f8eb-1680-4914-8057-d3cc3af629a8)

**Comment by troyrollins** [comment]
Same thing I'm seeing. It doesn't appear to have an update to 1.4.x from my end either.

**Comment by joshuatazrein** [comment]
Yeah, this is very weird. I'll try updating this again.

**Comment by joshuatazrein** [comment]
This should work now.

**Comment by SettingDust** [comment]
works :D. GJ
