### ISSUE TITLE
Weekly Review

### ISSUE THREAD

**Issue by cw594** [joshuatazrein/obsidian-time-ruler#62]
I'm just staring to use this plugin this morning, and I can only see the completed tasks in the task search bar by choosing the status as "X". Is there a method to see the completed tasks as Weekly review? OR how can the plugin interact with Tasks and Full Calendar? I can not see the tasks update in these two plugin when I set the tasks in this plugin. 
Thank you so much.

**Comment by joshuatazrein** [comment]
My understanding is that Full Calendar has to be manually reloaded, whereas Time Ruler automatically detects changes in notes. Tasks plugin should probably show the updates if you reload / close or open notes. 

TR doesn't support seeing past dates right now. Can you describe the weekly review idea further?

**Comment by joshuatazrein** [comment]
Added to changelog

**Comment by joshuatazrein** [comment]
Supported in `1.7.0`: search completed tasks by week
