### ISSUE TITLE
update from 1.3.1 to 1.4.0 lost my ics setting

### ISSUE THREAD

**Issue by pcause** [joshuatazrein/obsidian-time-ruler#63]
**Describe the bug**
Just upgraded to 1.4 and an ics calendar i had set is gone in settings

**To Reproduce**
just did the upgrade with an ics calendar in the settings before upgrade

**Expected behavior**
setting would be carried voer

**Obsidian Version:** 
- [ ] Mobile
- [ x] Desktop

**Comment by joshuatazrein** [comment]
Yeah, it's strange that this happens, it would have to be an issue opened with the main Obsidian team. I'll put something on the forum.
