### ISSUE TITLE
Full Calendar format won't show tasks from daily note on scheduled time

### ISSUE THREAD

**Issue by MCWopper** [joshuatazrein/obsidian-time-ruler#67]
**Describe the bug**
As I was testing the due issue I previously posted I noticed that with the full calendar format tasks in the dialy note are always placed in the full day section of Time Ruler and not on the scheduled time.

**To Reproduce**
1. Setup Time Ruler to use Full Calendar format
2. Open a daily note
3. Create task
4. Set a scheduled time like 15:00
5. Notice that task isn't displayed at time but at the top
6. Restart Obsidian
7. Task now at the correct time
8. Edit task
9. Task no longer at the correct time

**Expected behavior**
When a task has time inside its scheduled metadata it should appear at that time in the Time Ruler window

**Obsidian Version:** 
- [v1.4.14] Desktop

**Comment by joshuatazrein** [comment]
The property `[startTime:: 15:00]` for example works when I test it.
