### ISSUE TITLE
Timeline view / Gantt chart

### ISSUE THREAD

**Issue by imeed166** [joshuatazrein/obsidian-time-ruler#7]
**Is your feature request related to a problem? Please describe.**
- A date-based task overview that allows me to see all of my tasks for a specific period of time (weeks to months).
- A task overview that can handle tasks that span multiple days. This means that I can see all the tasks that I need to complete for a particular project, even if the project takes more than one day to complete.

**Describe the solution you'd like**
I want to see my tasks in a timeline view, and preferably in the main pane, not in the sidebar.

**Describe alternatives you've considered**
normal calendar view.

**Comment by joshuatazrein** [comment]
This is definitely something I'm thinking about, though Gantt charts don't currently fit with the architecture of the plugin. I'm considering improvements to the current calendar view that will enable more of a zoomed-out approach.

For now, I would suggest using the "Upcoming" view for due dates, which shows all dates in a collapsed timeline view (you can also supply a custom filter in Settings to show only a specific project). Also, on Desktop you can drag the Time Ruler view from the side panel into the main view to see an expanded, 4-day view.

**Comment by joshuatazrein** [comment]
Ok—just made another update after thinking this over. The way you can now do this in Time Ruler is by having "start" dates be the beginning of tasks and "due" dates be the end of multi-day tasks. Tasks will now show up each day after they start and before they are due, and can be rescheduled this way. I think this is the best way to integrate the Gantt chart idea with the current setup of Time Ruler. 

Let me know if this works or if you have any other ideas!
