### ISSUE TITLE
Timezone support for events coming from Calendars

### ISSUE THREAD

**Issue by kalbasit** [joshuatazrein/obsidian-time-ruler#70]
Hello,

Thank you for the great plugin; I love it so far! I added my work calendar (secret iCal from Google Calendar sharing), and it loaded events correctly, for the most part. Some of the events were sent from India and have the India Timezone attached to the event; When Time Ruler pulls this specific event, it shows to be scheduled at 9 PM instead of 8:30 AM.

<img width="514" alt="Screenshot 2023-10-23 at 1 52 15 PM" src="https://github.com/joshuatazrein/obsidian-time-ruler/assets/87115/b9fcb04f-0342-41b8-ad49-41ae272a9166">
<img width="782" alt="Screenshot 2023-10-23 at 1 49 25 PM" src="https://github.com/joshuatazrein/obsidian-time-ruler/assets/87115/7869d7a8-a4ba-499e-89ec-63cca363f661">

<img width="371" alt="Screenshot 2023-10-23 at 1 49 36 PM" src="https://github.com/joshuatazrein/obsidian-time-ruler/assets/87115/e4d886f7-2fac-47b6-816d-67df966f1eb7">

**Comment by kalbasit** [comment]
Raw event with details omitted.

```ical
BEGIN:VCALENDAR
BEGIN:VEVENT
DTSTART;TZID=Asia/Kolkata:20231024T210000
DTEND;TZID=Asia/Kolkata:20231024T213000
RRULE:FREQ=WEEKLY;BYDAY=TU
DTSTAMP:20231023T205553Z
ORGANIZER;CN=[omitted]
UID:[omitted]
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=[omitted];X-NUM-GUESTS=0:mailto:[omitted]
X-GOOGLE-CONFERENCE:[omitted]
CREATED:20220118T181438Z
DESCRIPTION:[omitted]
LAST-MODIFIED:20231023T204757Z
SEQUENCE:1
STATUS:CONFIRMED
SUMMARY:Eng Hangout
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR
```

**Comment by joshuatazrein** [comment]
Would you prefer the event be shown relative to the current timezone, or all show up when they are scheduled regardless of timezone?

**Comment by pcause** [comment]
yes, events should be displayed in the current timezone.

**Comment by joshuatazrein** [comment]
This should work in 1.5.2.

**Comment by kalbasit** [comment]
I can confirm it's fixed for some events, but not for others. I'm not sure why Google Calendar uses two different styles for the ical event, but I went ahead and isolated a couple of examples (coming directly from my own calendar) and put it all in a jsfiddle for you. Let me know if you need anything else to make this work.

https://jsfiddle.net/kalbasit/gz8pxujo/  You'll notice in my jsfiddle the local timezone is hardcoded to mine but you can comment that line and uncomment the one above to get the one in your local timezone.

**Comment by pcause** [comment]
> seems to be fixed

sorry, thought i was responding to another fix.  haven't tested by will

**Comment by kalbasit** [comment]
https://github.com/peterbraden/ical.js/issues/50 looks like the ical library you're using doesn't really handle this style of timezone.

**Comment by joshuatazrein** [comment]
Yes, I'll probably have to parse the data myself or find a new one

**Comment by pcause** [comment]
actually,  the library is apache 2 license.  just use and modify.  you can also submit a pull back to the original to add the capability.  less work.

one thing to remember is that the starting/ending times can be in different timezones

**Comment by joshuatazrein** [comment]
Alright, I'll give that a shot.

**Comment by pcause** [comment]
I did a quick look and for some reason the code uses a regex to pick up the date.  Not sure why as the date function of javascript ccan parse an ISO date (including timezone).  You might also want to look at this obsidian pluging that parses ical entries.  Haven't checked if it handles timezones though

**Comment by joshuatazrein** [comment]
I'll close this issue until someone wants to PR it.
