### ISSUE TITLE
error in 1.5.1

### ISSUE THREAD

**Issue by pcause** [joshuatazrein/obsidian-time-ruler#71]
**Describe the bug**
I got an error popup (invalid dataview query).  None of my tasks displayed but ics calendar is displayed partially.  Saw this in the developer console

2
plugin:dataview:18905 Uncaught (in promise) Error: Failed to parse query in 'pagePaths': Error: 
-- PARSING FAILED --------------------------------------------------

> 1 | "" and ()
    |         ^

Expected one of the following: 

'!', '(', '-', 'csv(', 'outgoing(', file link, string, tag ('#hello/stuff')

    at DataviewApi.pagePaths (plugin:dataview:18905:19)
    at DataviewApi.pages (plugin:dataview:18927:21)
    at ObsidianAPI.loadTasks (plugin:time-ruler:68430:28)
    at reload (plugin:time-ruler:70471:19)
﻿

I was glad to see the logging of every task gone, but perhaps catch the error and log the task on a parse error.  Could be I have a bad task or a bug or both, right?

Note:  today had an all day item from my ics calendar and one item with a timezone that was not my timezone.

**Comment by joshuatazrein** [comment]
Yep so sorry about this issue. I've fixed in 1.5.2.
