### ISSUE TITLE
CONTRIBUTION: How do you develop the plugin locally?

### ISSUE THREAD

**Issue by kalbasit** [joshuatazrein/obsidian-time-ruler#73]
I wanted to debug what was happening in #70 for me locally but I couldn't figure out how to do that. It would be great if you could document how to develop locally in the CONTRIBUTING.md file.

**Comment by joshuatazrein** [comment]
Fork the repository on GitHub, then create a pull request: https://docs.github.com/en/get-started/quickstart/fork-a-repo

**Comment by kalbasit** [comment]
> Fork the repository on GitHub, then create a pull request: [docs.github.com/en/get-started/quickstart/fork-a-repo](https://docs.github.com/en/get-started/quickstart/fork-a-repo)

I didn't mean the basics of GitHub and pull requests. I meant for example how to build it?

```console
❯ npm run build

> obsidian-time-ruler@1.0.0 build
> cd ../../ && DIR=time-ruler npm run build

npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/yl/code/repositories/github.com/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/yl/code/repositories/github.com/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in: /Users/yl/.npm/_logs/2023-10-25T20_09_52_561Z-debug-0.log
```

**Comment by joshuatazrein** [comment]
Ahhhh yes, sorry about that. It's in a monorepo, so all the packages are hosted there. Let me find what is used.

**Comment by joshuatazrein** [comment]
Plugin development is now possible locally, I unified the assets. Let me know if you have questions!
