### ISSUE TITLE
use tasks API when task clicked

### ISSUE THREAD

**Issue by pcause** [joshuatazrein/obsidian-time-ruler#74]
**Is your feature request related to a problem? Please describe.**

I want to be able to easily get to a task and also handle things like recurring items, complex statuses and the like.  right now if I click a task, the note with the task is opened.  tasks has an API to allow the tasks modal to be invoked.  if you could add an option so we could have clicking on an item open the tasks model it becomes easier to use the 2 together and solves the recurrence problem.  also, if this is enabled, clicking the checkbox also pops up the modal.

**Comment by joshuatazrein** [comment]
I like this idea, I added it to the roadmap.

**Comment by pcause** [comment]
thanks!  Great plugin and you are very responsive
