### ISSUE TITLE
Rendering front matter field as file name

### ISSUE THREAD

**Issue by cervera-queiroz** [joshuatazrein/obsidian-time-ruler#76]
**Is your feature request related to a problem? Please describe.**

I'm currently using the unique ID method for naming my files. The challenge is when adding a new note from Time Ruler, I retrieve the file names (e.g., 20231031071512) which makes it hard to get the context and select the note to add the new task.

**Describe the solution you'd llike.**
Have an option on the setting that alllows rendering a specific YAML field for the note name.

**Describe alternatives you've considered**
---

**Additional context**
Unique ID is a popular naming convention used across Obsidian users (especially with the Zettelkasten method). 

P.S. Great plugin!

**Comment by joshuatazrein** [comment]
Added alias support to the changelog!
