### ISSUE TITLE
Error importing esbuild (npm run dev)

### ISSUE THREAD

**Issue by REHvision** [joshuatazrein/obsidian-time-ruler#77]
**Describe the bug**
`npm run dev` throws the following error:
`Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'esbuild.js' imported from /home/.../.obsidian/plugins/time-ruler/esbuild.config.mjs`

**To Reproduce**
1. clone the repository
2. `npm install`
3. `npm run dev`

**Expected behavior**
`npm run dev` should be able to run without error (as described in the CONTRIBUTING guide) or missing dev setup steps should be documented.

**Obsidian Version:** 
- [ ] Mobile
- [x] Desktop 1.4.16

**Additional context**

As far as I know imports need to include the file extensions (e. g. `import from 'index.js'` instead of `import from 'index'`) but I haven't figured it out yet to make it start.

It would be great if you can have a look into this :pray:
Very promising plugin by the way! :wink:

**Comment by joshuatazrein** [comment]
Actually with Typescript you can't include file extensions in imports. Possibly the file is missing from the repo? I will see if I can reproduce the error.

**Comment by joshuatazrein** [comment]
This is fixed in the repo now, just some missing packages.
