### ISSUE TITLE
Display tasks with multiple schedule times

### ISSUE THREAD

**Issue by faranvir** [joshuatazrein/obsidian-time-ruler#78]
Would it be possible to allow multiple scheduled times? This is a feature I like from Sunsama that would be great to use in the obsidian workflow, so I can schedule, say, an hour a day for a week for a given task (or two separate time blocks in a given day to focus on a task), and then tick it off which ever day I manage to complete it. This is different to recurring tasks which can be completed each day, but needs to be started anew each day.

**Comment by joshuatazrein** [comment]
I like this idea a lot, but the whole architecture is based around a single scheduled time. A workaround that's more TR-native is to create subtasks for each scheduled time, they will show up with the parent task. Let me know if that would work. 

The alternate thing for routines/repeating tasks is to create a Daily Note template with those tasks pre-filled. Then each day a new set of tasks is created.
