### ISSUE TITLE
Can't define a file filter

### ISSUE THREAD

**Issue by da-the-dev** [joshuatazrein/obsidian-time-ruler#80]
**Describe the bug**
Cannot define a custom filter in the settings 

**To Reproduce**
1. Go to settings
2. Define the Custom Filter as "#ruler"
3. Reload in Time Ruler
4. See error in console

**Expected behavior**
Only files files with tag `#ruler` in the front matter should be used to scan for tasks

**Screenshots**

**Obsidian Version:** 
- [ ] Mobile
- [X] Desktop

**Additional context**
Here's the error log:
```
plugin:time-ruler:68662 TypeError: Cannot destructure property 'folder' of '(intermediate value)' as it is null.
    at getDailyNoteInfo (plugin:time-ruler:68648:11)
    at async reload (plugin:time-ruler:70454:27)
```

**Comment by joshuatazrein** [comment]
This specific error is fixed in upcoming but it doesn't relate to the `#ruler` tag...is that filter working?

**Comment by da-the-dev** [comment]
> This specific error is fixed in upcoming but it doesn't relate to the `#ruler` tag...is that filter working?

No, not really, when I set this filter I get an error in console and no tasks are shown in time ruler

**Comment by joshuatazrein** [comment]
Ok, this should be fixed. Let me know if not.

**Comment by da-the-dev** [comment]
Can confirm, this works. Thank you a lot!
