### ISSUE TITLE
Cannot change display text with |

### ISSUE THREAD

**Issue by da-the-dev** [joshuatazrein/obsidian-time-ruler#81]
**Describe the bug**
I can use [[Wikilinks]] as note texts. However, if I use `|` to change display text, the replacement is not replaced in Time Ruler

**To Reproduce**
Example: 
`[[Upcoming assignments#^e6cffb|Physics HW]]`
Is displayed as:
`Upcoming assignments ^e6cffb`

**Expected behavior**
Should be displayed as:
`Physics HW`

**Screenshots**

![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/39898616/81381a13-b5d3-4449-bdf2-1245c66a383a)

**Obsidian Version:** 
- [ ] Mobile
- [x] Desktop

**Comment by joshuatazrein** [comment]
Added to roadmap, thanks for the suggestion.

**Comment by joshuatazrein** [comment]
Supported in `1.7.0`
