### ISSUE TITLE
大佬，有没有打算加一个日历视图啊，full calendar和tasks之间太难融合了，tasks相关的插件一直很缺少一个好用的日历视图

### ISSUE THREAD

**Issue by lxmwwl** [joshuatazrein/obsidian-time-ruler#82]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by joshuatazrein** [comment]
The plugin is a calendar view, if you drag it to the main tab you can view 4 days in a row.
