### ISSUE TITLE
In main tab, not all days are displayed after upgrade to 1.5.3

### ISSUE THREAD

**Issue by gr2mx** [joshuatazrein/obsidian-time-ruler#83]
**Describe the bug**
When having time ruler open in the main tab, it is impossible to display more than 3 days, even though the bottom scrollbar adjusts.

**To Reproduce**
1. Open time ruler in main tab
2. Click on the right arrow after tomorrow
3. Observe that no new days are displayed and that the scrollbar at the bottom has adjusted
4. The behavior persists when you click on the right arrow multiple times (though after the second click a third day appears, that third day should have been displayed after the first click . I have not been able to display more than three days)

**Expected behavior**
Every day is displayed

**Screenshots**
![Screenshot_20231124_100733-1](https://github.com/joshuatazrein/obsidian-time-ruler/assets/1076494/8a9bb464-8b2f-49e1-baa2-db7c5a91c6e3)
![Screenshot_20231124_101614](https://github.com/joshuatazrein/obsidian-time-ruler/assets/1076494/37a69ee9-13f1-43df-8dc8-f8c9d481a276)

**Obsidian Version:** 
- [ ] Mobile
- [X] Desktop

**Additional context**
- was working fine with the versions previous to 1.5.3

Thanks for time ruler! I love it and it has been a great boon to how I use obsidian and how I organize my life!

**Comment by higalpe** [comment]
Yes, same issue here.

**Comment by joshuatazrein** [comment]
This was part of optimizing dates, so only ones which are in view are rendered—I will add in detection of how wide the viewport is

**Comment by joshuatazrein** [comment]
Fixed in 1.6.0
