### ISSUE TITLE
Calendar grid view

### ISSUE THREAD

**Issue by higalpe** [joshuatazrein/obsidian-time-ruler#84]
It would be a nice improvement to have a view not only linear of the days but the full month. Like the logseq Agenda plugin:

![imagen](https://github.com/joshuatazrein/obsidian-time-ruler/assets/42850993/305bc268-6218-4573-93af-28d4048b3f75)

**Describe the solution you'd like**
Show only the scheduled and due tasks for each day and be able to drag and drop them to different days.

I think this is the feature that [this request](https://github.com/joshuatazrein/obsidian-time-ruler/issues/82) was trying ot explain.

Thanks.

**Comment by joshuatazrein** [comment]
This has been added to `1.7.0`

**Comment by wwjCMP** [comment]
I have the same issue. It seems there is no calendar view.

**Comment by j-palindrome** [comment]
There is only a view by week; sorry for the misunderstanding.
