### ISSUE TITLE
Make obsidian omnipotent in daily management - Full functionalities similar to ticktick and toggl track

### ISSUE THREAD

**Issue by LBWNB55KYYDS** [joshuatazrein/obsidian-time-ruler#86]
implement all functionalities in
ticktick https://help.ticktick.com/articles/7054286604315131904
toggl track https://toggl.com/track/

Enhance Obsidian to be an all-encompassing solution for daily management, incorporating a comprehensive set of features akin to both TickTick and Toggl Track. This includes integrating a daily timer, Pomodoro technique, Eisenhower Matrix (4-quadrant time management system), habit tracker, task archiving, and the ability to create events seamlessly under the daily folder (Daily notes folder/folder named with the current date/Events).

![fed50fc4a07de1bf9d8d630bb0d3bf1b](https://github.com/joshuatazrein/obsidian-time-ruler/assets/103039908/ade09bbd-14ce-4251-bb59-e91283f8cd02)
![f61ef428c7cece5b3c24dc1f87482cc4](https://github.com/joshuatazrein/obsidian-time-ruler/assets/103039908/2ab25cb2-a91a-469b-a140-f2e6aefeb868)
![a6743c84a292de81aca3cf254c2829ae](https://github.com/joshuatazrein/obsidian-time-ruler/assets/103039908/f3d9dad8-b39f-4611-b2f3-9ec2fd6b8caf)
![OIP](https://github.com/joshuatazrein/obsidian-time-ruler/assets/103039908/47cacf8e-0f3a-4755-b30b-db90bdda8d27)
![feature-mobile-oneclick](https://github.com/joshuatazrein/obsidian-time-ruler/assets/103039908/8c282d56-a2a8-42df-92c0-2ab891176bd8)

**Comment by LBWNB55KYYDS** [comment]
https://forum.obsidian.md/t/make-obsidian-omnipotent-for-daily-management/72112

**Comment by joshuatazrein** [comment]
This is a good aspiration but out of scope for the plugin. Some features will be added.
- Time Ruler currently supports the Pomodoro Timer which is fully customizable for length as well. 
- You can create tasks in Daily notes automatically with the "+" button
- Eisenhower Matrix settings would be nice, I'll think about those.

**Comment by joshuatazrein** [comment]
I agree, time tracking would be pretty cool. I can add a feature with the Timer where when you check off a task it sets the task's length based on the length of time spent, then resets the timer. Completed/weekly review is upcoming in next version

**Comment by LBWNB55KYYDS** [comment]
Yes that would be great! I'm looking forward to seeing that improvements! Thank you!
