### ISSUE TITLE
Markdown Support?

### ISSUE THREAD

**Issue by Kirxii** [joshuatazrein/obsidian-time-ruler#89]
**Is your feature request related to a problem? Please describe.**
It would be nice if there was markdown support in Time Ruler since I use markdowns for tasks.

**Describe the solution you'd like**
Supporting markdown.

**Comment by joshuatazrein** [comment]
Like bold/italic/underline formatting?

**Comment by Kirxii** [comment]
Yes, the formattings.

**Comment by joshuatazrein** [comment]
Added to roadmap!
