### ISSUE TITLE
Tasks recurrence rule moved to description when dragging a task

### ISSUE THREAD

**Issue by gypsyav** [joshuatazrein/obsidian-time-ruler#9]
**Describe the bug**
- When dragging a task from one time to another when using Tasks format, any recurrence rule becomes part of the description and no longer works in Tasks.

**To Reproduce**
1. Set format to Tasks
2. Create task with recurrence
3. Go to Hourly View
4. Drag task to new time slot
5. Open task in Tasks modal. The recurrence rule has become part of the description and are no longer set in Tasks

**Expected behavior**
The recurrence rule would be left in place
**Screenshots**
Original Task
![TaskBeforeDragNDrop](https://github.com/joshuatazrein/obsidian-time-ruler/assets/26289654/98dc69fe-4521-47e3-b050-883848e8f36e)

Task After Drag and Drop
![TaskAfterDragNDrop](https://github.com/joshuatazrein/obsidian-time-ruler/assets/26289654/fdbd9d00-ed1f-4954-ab95-0a2650829470)

**Obsidian Version:** 
- [ ] Mobile
- [x] Desktop

**Additional context**

**Comment by joshuatazrein** [comment]
Thanks for reporting the issue! I'll fix this in the next day or so.

**Comment by gypsyav** [comment]
I discovered links are also stripped during drag and drop, that might be related to this issue. Do you want me to file another report?

And thank you for the work you've put in on this. This plugin is exactly what I've been looking for.

**Comment by joshuatazrein** [comment]
Is this pertaining to internal `[[]]` links ur URLs `()[]`? I can fix that too—these are both pretty simple fixes.
