### ISSUE TITLE
Improve task drag and drop feature

### ISSUE THREAD

**Issue by higalpe** [joshuatazrein/obsidian-time-ruler#90]
(I do not know if this is a bug or a feature request actually)

**Describe the bug**
If a task has long name, it is complicated to drag and drop it to another day. 

**To Reproduce**
Create a task, for example: - [ ] This is a task with a long description. It is complicated to drag and drop it. [scheduled:: 2023-12-12 ]

So far, you only can drag and drop when you are able to get this grabbing hand cursor:
![imagen](https://github.com/joshuatazrein/obsidian-time-ruler/assets/42850993/7fd27e40-62dc-4991-8d63-1723d52b43a7)

But most of the time, the cursor will look like this and it means that the drag and drop option is not possible from that location:
![imagen](https://github.com/joshuatazrein/obsidian-time-ruler/assets/42850993/59bcd747-5218-464a-bf5a-23c10db7e661)

**Expected behavior**
To be able to drag and drop the task, no matter where the cursor is when you click on the task name.

**Screenshots**

**Obsidian Version:** 
- 1.5.1 (Desktop)

Thank you.

**Comment by joshuatazrein** [comment]
There's a minimum width of 24px after the title which you should use to drag the task. Not ideal, I'll try to improve how that works. Added to changelog

**Comment by joshuatazrein** [comment]
Update: Tasks will have a special handle at the right for easier dragging & dropping
