### ISSUE TITLE
Add a setting to prevent the current day/time from being truncated

### ISSUE THREAD

**Issue by jjmaldonis** [joshuatazrein/obsidian-time-ruler#94]
Awesome plugin!

Currently, when I schedule a task and didn't complete it on time, the task disappears from the Time Ruler calendar view because the current day's view begins at the current time of day.

I'd like a toggle in the setting to prevent the current day's view from beginning at the current time of day. Instead, I always today's view to begin at the beginning of the day (which I have set to 6am). This allows me to see what I've completed and allows me to move any tasks I didn't complete to a later time.

Also, if I am currently working on a task that started at 12:30pm and it's now 12:35pm, I can't see the task because of the same viewing issue.

**Comment by joshuatazrein** [comment]
The Now view will now show what you've completed in the past.

**Comment by jjmaldonis** [comment]
Hey, it's okay to have this in the Now view, but I want to see the completed tasks in the current day's calendar view because it's useful to see when the task was scheduled during the day.

I found [this](https://github.com/joshuatazrein/obsidian-time-ruler/blob/master/src/components/App.tsx#L155) code which seems to be relevant, but without spending a lot more time digging in I can't create a PR to do this myself.

**Comment by joshuatazrein** [comment]
Use the Past view for that, it shows all completed tasks when they were schedule for time tracking.

**Comment by jjmaldonis** [comment]
Is it possible to view the Past and Future views at the same time?

**Comment by joshuatazrein** [comment]
Not currently that is a good idea though. Show Completed Tasks setting allows you to see stuff completed today

**Comment by joshuatazrein** [comment]
“Show Completed Tasks” lets you see both, I can look into improving it
