### ISSUE TITLE
Updating Time by drag-and-drop updates using wrong format

### ISSUE THREAD

**Issue by ChayseSmith** [joshuatazrein/obsidian-time-ruler#99]
**Describe the bug**
I have the setting for "Preferred Field Format" set to "Day Planner" as I like to manage the task times in that format.
The tasks show up correctly in the timeline view, and for their correct duration, but when moving the tasks around using the timeline, it ignores the text at the beginning, and adds "[startTime:: x]" and "[length:: x]" fields to the task which I think is a bug.

**To Reproduce**
- Steps to reproduce the behavior:
- Create a task with a "scheduled date" of today, and set the text of the task to "13:00 - 13:30" (make sure the actual time you put is in the future)
- Observe the task is created with the correct duration in the "now -----" timeline view
- Move the "30m" time to a further time in the future
- Observe the text in the task now shows "13:00 - 13:30 TASK DESCRIPTION [startTime:: 13:00] [length:: 1hr]"

**Expected behavior**
I would have expected the times in the prefix of the task to be updated with the new content

**Screenshots**

**Obsidian Version:** 
- [ ] Mobile (haven't tested it, but believe it's not OS specific)
- [x] Desktop

**Additional context**

**Comment by joshuatazrein** [comment]
Thanks, I'll take a look at this!
